spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5440/hm?currentSchema=medical}
    username: ${DATABASE_USER:my_user}
    password: ${DATABASE_PASSWORD:my_password}
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: medical

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: medical
    show-sql: true
  flyway:
    enabled: true
    locations: db/migrations


server:
  port: 8280
