spring:
  datasource:
    url: ${DATABASE_URL1}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    driverClassName: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  cache:
    type: redis
    redis:
      time-to-live: 360000
      key-prefix: medical, abs
  redis:
    password: ${REDIS_PASSOWORD}
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}

host:
  userclient:
    apiHost: http://health-management-user-api.herokuapp.com
server:
  port: 8280
